env:
  es2017: true
  browser: true
  commonjs: true

extends: ['htmlacademy/es6', 'plugin:react/recommended', 'plugin:json/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react', 'json', 'html']

settings:
  react:
    version: '16'

rules:
  indent: [error, 2]
